### ISSUE TITLE
Support `X-Params` and `X-Components`

### ISSUE THREAD

**Issue by chrisdotcode** [JaninaWibker/parse-ical#6] opened 2024-08-18 04:28 UTC
Hey @JaninaWibker, it's me again :wink:

At some point, I'd like to contribute some code, but in the interim, I've discovered another missing feature (P.S.: is the plan to implement things on an "as-discovered" basis, what we are doing now (i.e.: once we discover somewhere `parse-ical` is not up to spec, we fix it)? That seems like a sensible way to do less up-front work compared to covering the entire spec at once, IMO.

In this case, I'm working with sensitive data I can't share directly, but, I can say a `VEVENT` `LOCATION` has an `X Param` attached, which *is* supported (via `other-param`), [as per the spec](https://www.rfc-editor.org/rfc/rfc5545#page-88).

The reason I asked about proceeding on an "as-discovered" basis is because it seems to be more sensible to add `X Param` support for *every* component supports them in one logical PR, rather than piecemeal, but that would of course require more effor than *just* updating `VEVENT`'s `LOCATION`.

I don't have time this exact second to look through all of the components in the spec (or at least the ones `parse-ical` currently supports) to see which do and don't take `X Param`s, but I wanted to let you know that at times `X Param` component support may be obscured. For example, `VEVENT` `LOCATION` does NOT list `x-param` directly, but rather takes an `other-param`, which itself can contain `X Param` values. Also, `other-param` can be repeated, so it indirectly supports having numerous `X Param`s.

~Also, as hinted at, I _think_ `X-Components` exist, but I don't have enough time to check the spec this moment. I certainly see something that looks like one in my data, if I'm looking at it right.~ Yes, `X-Components exist, see next comment.

Let me know what you think, and thanks again for the great lib!

**Comment by chrisdotcode** [comment] 2024-08-18 04:36
Found [`X-Components`](https://www.rfc-editor.org/rfc/rfc5545#page-52):

```
       component  = 1*(eventc / todoc / journalc / freebusyc /
                    timezonec / iana-comp / x-comp)

       iana-comp  = "BEGIN" ":" iana-token CRLF
                    1*contentline
                    "END" ":" iana-token CRLF

       x-comp     = "BEGIN" ":" x-name CRLF
                    1*contentline
                    "END" ":" x-name CRLF

   An iCalendar object MUST include the "PRODID" and "VERSION" calendar
   properties.  In addition, it MUST include at least one calendar
   component.  Special forms of iCalendar objects are possible to
   publish just busy time (i.e., only a "VFREEBUSY" calendar component)
   or time zone (i.e., only a "VTIMEZONE" calendar component)
   information.  In addition, a complex iCalendar object that is used to
   capture a complete snapshot of the contents of a calendar is possible
   (e.g., composite of many different calendar components).  More
   commonly, an iCalendar object will consist of just a single "VEVENT",
   "VTODO", or "VJOURNAL" calendar component.  Applications MUST ignore
   x-comp and iana-comp values they don't recognize.  Applications that
   support importing iCalendar objects SHOULD support all of the
   component types defined in this document, and SHOULD NOT silently
   drop any components as that can lead to user data loss.
```

**Comment by chrisdotcode** [comment] 2024-08-18 04:40
Sorry, it is only my presumption that `parse-ical` does not yet support `X-Components` (and that they would not parse with `transform`) simply because of the lack of `X Param` support. I may be incorrect, and `parse-ical` might already support `transform`ing into `X-Component`. Let me know.

**Comment by JaninaWibker** [comment] 2024-08-20 11:39
I'm sorry I'm really not sure how exactly a `X-Component` or `X-Param` would look like. From what I gathered there are the following possibilities:
- `BEGIN:X-COMPONENT [...] END:X-COMPONENT` somewhere
	- in a vCalendar?
	- in a vEvent?
- `LOCTION;X-PARAM=something:[...]`

Could you construct some kind of example which shows both?

**Comment by chrisdotcode** [comment] 2024-08-21 04:02
Sure! Here you go:

Note `X-LIC-LOCATION` and `X-APPLE-CREATOR-IDENTITY` (because this was created using the iPhone calendar).

```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:XXX
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:XXX
BEGIN:VTIMEZONE
TZID:America/New_York
LAST-MODIFIED:XXX
X-LIC-LOCATION:America/New_York
TZUNTIL:XXX
BEGIN:DAYLIGHT
TZNAME:EDT
TZOFFSETFROM:XXX
TZOFFSETTO:XXX
DTSTART:XXX
RRULE:XXX
END:DAYLIGHT
BEGIN:STANDARD
TZNAME:EST
TZOFFSETFROM:XXX
TZOFFSETTO:XXX
DTSTART:XXX
RRULE:XXX
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
X-APPLE-CREATOR-IDENTITY:com.apple.mobilecal
XXX
END:VEVENT
END:VCALENDAR
```

Anything marked `XXX` is something I've snipped out from my original data.

**Comment by chrisdotcode** [comment] 2024-08-21 04:27
Found some more doc in the spec:

[X-Params](https://www.rfc-editor.org/rfc/rfc5545#section-3.8.8.2)

**Comment by chrisdotcode** [comment] 2024-08-21 04:33
I admit that the X-Components doc isn't very clear, and from an initial reading of the spec, I would also arrive me at the conclusion you arrived at, but the actual way it seems to be used seems to be NOT with their own BEGIN and END tags, but just as regular components, like I have from my example (taken from real data) above.

**Comment by JaninaWibker** [comment] 2024-08-24 16:27
I am not very inclined to add `X-LIC-LOCATION` to `VTIMEZONE` as something that gets parsed and interpreted by the library as right now timezone related things are basically ignored, or rather handled by the browser which has a proper TZ database (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

However I think this info shouldn't be discarded if present but at least exposed via a `rest` property somewhere. I'll look into how that would work out in practice.

Regarding the X-Params (example: `X-NUM-GUESTS`) and X-Components (example: `X-APPLE-CREATOR-IDENTITY`), these work as intended already:
- `X-*` as well as other unknown components get put in the `rest` object of an event:
```js
rest: {
  'X-APPLE-CREATOR-IDENTITY': [
    {
      value: 'com.apple.mobilecal',
      parameters: {}
    }
  ]
}
```
- this is an example of how `ATTENDEES` gets parsed with `X-NUM-GUESTS=0`:
```js
 attendees: [{
  value: 'mailto:alice@example.com',
  parameters: {
    CN: 'Alice',
    CUTYPE: 'INDIVIDUAL',
    EMAIL: 'alice@example.com',
    PARTSTAT: 'NEEDS-ACTION',
    ROLE: 'REQ-PARTICIPANT',
    RSVP: 'TRUE',
    'X-NUM-GUESTS': '0'
  }
}]
```

**Comment by JaninaWibker** [comment] 2024-08-24 16:29
I'll add a test to showcase this behaviour though, having some tests around as example input/output pairs is quite nice when browsing through a project

**Comment by JaninaWibker** [comment] 2024-08-24 16:52
I must admit I think I had the wrong mental model of how timezones work in ical. It seems that:
- `VTIMEZONE`, etc. register/define what each TZID means, thus daylight saving time, offset and what not
- the normal TZIDs mean nothing to ical (`Europe/Berlin`, etc.), they should be redefined if they are to be used. It is totally valid to define `Asia/Shanghai` as being the same as`America/Los_Angeles`. Even though that doesn't really make any sense it is still allowed/a valid thing to do.
- not specifying a timezone on each and every `DTSTART`, etc. leaves it up to the implementation to decide which timezone to use. Most likely `X-WR-TIMEZONE` if supported, otherwise probably GMT/UTC

In the interest of not overcomplicating things (which is very much what I want to do with this library as I found others a bit too boated) and covering the most common and simple use case first and foremost instead of every edge case I'll ignore this entirely and act as if:
- `X-WR-TIMEZONE` is the best indicator for what timezone to use (going by TZIDs known to the browser)
- If there are multiple `VTIMEZONE`s then ignore them
- If there is only one `VTIMEZONE` then pick its `TZID` and hope that it is a TZID known to the browser

This is against what the spec requires or wants, but should work out in most cases and my goal isn't to be fully spec compliant but rather have a simple interface which is easy to use, but doesn't necessarily cover every usecase.

**Comment by JaninaWibker** [comment] 2024-08-24 18:28
See `parse-ical@1.2.2`

I added the following:
- `definedTimezones` as part of the `metadata` of a calendar. This contains `X-LIC-LOCATION` if present, along with other specified properties
- a bit more thorough validation for `VTIMEZONE`, `VDAYLIGHT` and `VSTANDARD`

**Comment by JaninaWibker** [comment] 2024-09-01 12:45
Closed as completed

**Closed as completed by JaninaWibker** 2024-09-01 12:45 UTC

**Comment by chrisdotcode** [comment] 2024-09-04 00:06
Hey, @JaninaWibker, sorry to not get back to you! I missed the notifications. I'll upgrade and let you know how it all works.

Thanks again for working with me :)
